---
# tasks file for copy_key_files

- name: Removing /root/.ssh from target hosts
  file:
    path: "{{ rmt_ssh_dir }}"
    state: absent
  register: path_delete
  until: path_delete is not failed
  retries: 3
  delay: 5

- name: Re-creating /root/.ssh on target hosts
  file:
    path: "{{ rmt_ssh_dir }}"
    state: directory
    mode: 0700
  register: path_create
  until: path_create is not failed
  retries: 3
  delay: 5

- name: Copying SSH key files from localhost to target hosts
  copy:
    src: "{{ files_dir }}/{{ item.src }}"
    dest: "{{ rmt_ssh_dir }}/{{ item.dst }}"
    mode: 0600
  with_items:
    - { src: 'id_rsa', dst: 'id_rsa' }
    - { src: 'id_rsa.pub', dst: 'id_rsa.pub' }
    - { src: 'id_rsa.pub', dst: 'authorized_keys' }
  register: copy_result
  until: copy_result is not failed
  retries: 3
  delay: 5
