---
all:
  vars:
    ansible_connection: ssh
    ansible_user: root
    ansible_ssh_pass: c0ntrail123
    ansible_become_pass: c0ntrail123

    domain_suffix: 251.lab
    ntp_server: 192.168.244.12

    contrail_container_tag: "1910.23"

  children:
    contrail_hosts:

      children:
        command_hosts:
          hosts:
            command:
              ansible_host: 192.168.251.3

        controller_hosts:
          hosts:
              aio:
                ansible_host: 192.168.251.4

        appformix_hosts:
          hosts:
            appformix:
              ansible_host: 192.168.251.5
