---
# tasks file for install_common_packages

- name: Install common packages
  yum:
    name:
      - rsync
      - tcpdump
    state: present
  register: yum_result
  until: yum_result is not failed
  retries: 3
  delay: 5
  