---
# tasks file for copy_hosts_file

- name: Copying hosts.txt to /etc/hosts
  copy:
    src: "{{ files_dir }}/{{ hosts_file }}"
    dest: "{{ rmt_hosts_file }}"
    mode: 0644
  register: copy_result
  until: copy_result is not failed
  retries: 3
  delay: 5
