---
# tasks file for install_appformix_packages

- name: Install appformix packages
  yum:
    name:
      - libvirt
    state: present
  register: yum_result
  until: yum_result is not failed
  retries: 3
  delay: 5
